@base = http://localhost:3000

### Health
GET {{base}}/

### All contacts
GET {{base}}/contacts

### Anna
GET {{base}}/contacts/by-id?id=68d8a8514afd2b99fea12cb3

### Ethan
GET {{base}}/contacts/by-id?id=68d8a8f94afd2b99fea12cbc

### Mike
GET {{base}}/contacts/by-id?id=68d8a9554afd2b99fea12cc2